name: Build and Push Backend to ACR

on:
  push:
    branches: [ "main" ]
    # Only run this if files outside the frontend folders change
    paths-ignore:
      - 'index.html'
      - 'student.html'
      - 'admin.html'
      - 'student.js'
      - 'admin.js'
      - 'utils.js'
      - 'style.css'

jobs:
  build_and_push_acr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/hostel-allocation-app:${{ github.sha }} , ${{ secrets.ACR_LOGIN_SERVER }}/hostel-allocation-app:latest
        # Example tag: newhostelregistryxyz.azurecr.io/hostel-allocation-app:commitSHA123
        # Example tag: newhostelregistryxyz.azurecr.io/hostel-allocation-app:latest